/**
 * Bundles the Electron main and preload scripts.
 *
 * The API server is compiled in rather than shipped as a dependency tree: two
 * entry points, no `node_modules` resolution at runtime, and the exact same
 * `server/dist/server.js` the CLI runs. Only genuinely optional native add-ons
 * stay external — `ssh2` and `ws` already guard their requires with try/catch.
 */
import { copyFile, mkdir, rm } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import esbuild from 'esbuild';

const here = path.dirname(fileURLToPath(import.meta.url));
const desktopDir = path.resolve(here, '..');
const repoDir = path.resolve(desktopDir, '..');
const outDir = path.join(desktopDir, 'build');
const serverEntry = path.join(repoDir, 'server', 'dist', 'server.js');
const webIndex = path.join(repoDir, 'web', 'dist', 'index.html');

const shared = {
  bundle: true,
  platform: 'node',
  format: 'cjs',
  target: 'node20',
  sourcemap: true,
  logLevel: 'warning',
  // `electron` is provided by the runtime; the rest are optional native add-ons
  // that their libraries probe for and tolerate the absence of.
  external: ['electron', 'cpu-features', 'sshcrypto', 'bufferutil', 'utf-8-validate'],
  alias: { '@ssh-explorer/server-runtime': serverEntry },
  define: {
    'process.env.NODE_ENV': '"production"',
    // The API server is ESM and reads `import.meta.url` to locate its own
    // package.json. Electron's preload must stay CommonJS, so the expression is
    // rewritten to the CJS equivalent rather than switching the whole bundle.
    'import.meta.url': '__importMetaUrl',
  },
  plugins: [nativeAddons()],
};

/**
 * Prepended to the main bundle only.
 *
 * The guard has to run before any `require("electron")`: with
 * `ELECTRON_RUN_AS_NODE` set the runtime is plain Node, `electron` resolves to
 * the npm package's path string, and every later access fails with an unrelated
 * "cannot read properties of undefined". It must NOT be added to the preload —
 * a sandboxed preload gets a reduced `process`, so the check would be false
 * there and would kill the bridge.
 */
const MAIN_BANNER = [
  '/* SSH Explorer desktop shell — generated by desktop/scripts/build.mjs. Do not edit. */',
  'if (typeof process.versions.electron !== "string" || process.env.ELECTRON_RUN_AS_NODE) {',
  '  console.error("SSH Explorer must be started with Electron. Unset ELECTRON_RUN_AS_NODE and launch the app again.");',
  '  process.exit(1);',
  '}',
  'const __importMetaUrl = require("node:url").pathToFileURL(__filename).href;',
].join('\n');

/**
 * `ssh2` optionally requires a compiled `sshcrypto.node` inside a try/catch and
 * falls back to pure JavaScript when it is absent. esbuild cannot see the
 * try/catch, so any `.node` import is left alone and resolved (or not) at runtime.
 */
function nativeAddons() {
  return {
    name: 'native-addons',
    setup(build) {
      build.onResolve({ filter: /\.node$/ }, (args) => ({ path: args.path, external: true }));
    },
  };
}

async function ensurePrerequisites() {
  const missing = [];
  try {
    await import('node:fs/promises').then((fs) => fs.access(serverEntry));
  } catch {
    missing.push(`  - ${path.relative(repoDir, serverEntry)} (run: npm run build --workspace @ssh-explorer/server)`);
  }
  try {
    await import('node:fs/promises').then((fs) => fs.access(webIndex));
  } catch {
    missing.push(`  - ${path.relative(repoDir, webIndex)} (run: npm run build --workspace @ssh-explorer/web)`);
  }
  if (missing.length > 0) {
    throw new Error(`Missing build output:\n${missing.join('\n')}`);
  }
}

await ensurePrerequisites();
await rm(outDir, { recursive: true, force: true });
await mkdir(outDir, { recursive: true });

await esbuild.build({
  ...shared,
  entryPoints: [path.join(desktopDir, 'src', 'main.ts')],
  outfile: path.join(outDir, 'main.cjs'),
  banner: { js: MAIN_BANNER },
});

await esbuild.build({
  ...shared,
  entryPoints: [path.join(desktopDir, 'src', 'preload.ts')],
  outfile: path.join(outDir, 'preload.cjs'),
  banner: { js: '/* SSH Explorer preload — generated. Do not edit. */' },
});

// The window/taskbar icon has to sit next to the bundle because it is read at
// runtime from inside the asar archive.
await copyFile(path.join(desktopDir, 'resources', 'icon.png'), path.join(outDir, 'icon.png'));

console.log(`desktop shell built -> ${path.relative(repoDir, outDir)}`);
