/**
 * Sets the repository up for publication: the licence, the ignore rules, and the
 * `license` field in each manifest.
 *
 * The Apache-2.0 text is copied from a dependency that ships it verbatim rather than
 * retyped: a licence with a paraphrased clause is worse than no licence at all, because
 * it looks authoritative and is not.
 *
 * Run once: node tools/setup-license.mjs
 */
import { copyFileSync, readFileSync, readdirSync, writeFileSync } from 'node:fs';
import path from 'node:path';

const ROOT = path.resolve(import.meta.dirname, '..');
const YEAR = new Date().getFullYear();
const HOLDER = 'andrewwoolfi';

/** Finds a dependency that ships the exact Apache-2.0 text. */
function canonicalApacheText() {
  // Walk the installed tree rather than guessing package names: the packages that carry
  // the text are not the ones you would expect, and a hardcoded list silently rots.
  const found = [];
  const walk = (dir, depth) => {
    if (depth > 3) return;
    let entries;
    try {
      entries = readdirSync(dir, { withFileTypes: true });
    } catch {
      return;
    }
    for (const entry of entries) {
      const full = path.join(dir, entry.name);
      if (entry.isDirectory()) {
        walk(full, depth + 1);
        continue;
      }
      if (!/^LICENSE/i.test(entry.name)) continue;
      try {
        const text = readFileSync(full, 'utf8');
        if (
          text.includes('Apache License') &&
          text.includes('Version 2.0, January 2004') &&
          text.includes('TERMS AND CONDITIONS FOR USE, REPRODUCTION, AND DISTRIBUTION')
        ) {
          found.push({ file: full, text });
        }
      } catch {
        /* unreadable or binary */
      }
    }
  };
  walk(path.join(ROOT, 'node_modules'), 0);
  if (found.length === 0) {
    throw new Error('No dependency ships the Apache-2.0 text; refusing to invent one.');
  }
  // The smallest match is the plain licence; the big ones bundle notices alongside it.
  found.sort((a, b) => a.text.length - b.text.length);
  const best = found[0];
  return { name: path.relative(ROOT, best.file), text: best.text };
}

const { name: source, text } = canonicalApacheText();
// Normalise the trailing whitespace so the appended notice sits cleanly at the end.
const licence = `${text.trimEnd()}\n\n   Copyright ${YEAR} ${HOLDER}\n\n   Licensed under the Apache License, Version 2.0 (the "License");\n   you may not use this file except in compliance with the License.\n   You may obtain a copy of the License at\n\n       http://www.apache.org/licenses/LICENSE-2.0\n\n   Unless required by applicable law or agreed to in writing, software\n   distributed under the License is distributed on an "AS IS" BASIS,\n   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.\n   See the License for the specific language governing permissions and\n   limitations under the License.\n`;
writeFileSync(path.join(ROOT, 'LICENSE'), licence, 'utf8');
copyFileSync(path.join(ROOT, 'LICENSE'), path.join(ROOT, 'LICENSE.txt'));
console.log(`LICENSE written from ${source} (${licence.length} bytes)`);

const GITIGNORE = `# Dependencies and build output — regenerated by npm, never edited by hand.
node_modules/
server/dist/
web/dist/
desktop/build/

# Packaged applications: ~90 MB each, they belong in a release, not in history.
release/
*.blockmap

# Runtime state of a local run. \`secrets.json\` lives here, encrypted or not.
.ssh-explorer-qa/
.ssh-explorer/

# Scratch trees the QA driver and the mock SSH server create.
.mock-ssh-root/
.mock-ssh-root2/

# Artefacts of a QA run: they change on every run and describe one machine.
design/qa/mock.json
design/qa/mock2.json
design/qa/*-smoke.json
design/qa/*-e2e.json
design/qa/qa-run.txt
design/qa/qa2.txt

# Code-graph index.
.codebase-memory/

# Editor and OS noise.
.vscode/
.idea/
Thumbs.db
desktop.ini
*.log

# Never commit a real key, a real host list or a decrypted secret. The names are listed
# so that an accident is refused rather than noticed later.
secret.key
id_rsa
id_ed25519
`;
writeFileSync(path.join(ROOT, '.gitignore'), GITIGNORE, 'utf8');
console.log('.gitignore written');

for (const manifest of ['package.json', 'server/package.json', 'web/package.json', 'desktop/package.json']) {
  const file = path.join(ROOT, manifest);
  const json = JSON.parse(readFileSync(file, 'utf8'));
  json.license = 'Apache-2.0';
  json.author = json.author && json.author !== 'WooSSH Explorer' ? json.author : HOLDER;
  writeFileSync(file, `${JSON.stringify(json, null, 2)}\n`, 'utf8');
  console.log(`  ${manifest}: license=Apache-2.0`);
}
